### ISSUE TITLE
Run Problem

### ISSUE THREAD

**Issue by kubo10** [strelec/HP-4510s-fan-control#1]
Hi dear friend , 
I wanna try it on my HP Probook 6470b  ,but I got this error : 

```
fancontrol.rb:41:in ``': No such file or directory - acpi (Errno::ENOENT)
    from fancontrol.rb:41:in `get'
    from fancontrol.rb:93:in `block in <main>'
    from fancontrol.rb:78:in `loop'
    from fancontrol.rb:78:in `<main>'

```

Thanks for help

**Comment by strelec** [comment]
Requirements:

ruby >= 2.0
acpi

You probably miss the second package. I hope the script works anyways, because your laptop might have different registers.

**Comment by kubo10** [comment]
I run it but. Shell script don't wanna control my fan. I have ubuntu 15.10.

**Comment by strelec** [comment]
That is what I have thought.

For you laptop, you have to figure out the patterns yourself. Try experimenting with the command below, so try what happens if you echo 0 or 1 for different numbers (example for the number 4).

sudo echo 1 > /sys/devices/virtual/thermal/cooling_device4/cur_state
